# Generated by Django 3.0.6 on 2021-02-05 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizatori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='media/pictures')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 5, 14, 26, 44, 280780))),
            ],
        ),
    ]
