# Generated by Django 3.0.6 on 2021-02-05 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizatori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizatori',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 5, 14, 27, 54, 570966)),
        ),
    ]
