# Generated by Django 3.0.6 on 2021-02-08 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizatori', '0004_auto_20210205_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatori',
            name='cnp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizatori',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 8, 11, 53, 2, 163070)),
        ),
    ]
