# Generated by Django 3.0.6 on 2021-02-08 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizatori', '0005_auto_20210208_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizatori',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 8, 12, 33, 58, 967291)),
        ),
    ]
